# Generated by Django 2.2.6 on 2019-11-21 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wortschatz', '0015_auto_20191121_1205'),
        ('ausbildung', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antwort',
            name='user',
        ),
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fragetyp', models.IntegerField(default=(0, 'Para o seu idioma'), verbose_name='Tipo de pergunta')),
                ('Wortschatz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wortschatz.Wortschatz', verbose_name='Questão')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'unique_together': {('Wortschatz', 'Fragetyp')},
            },
        ),
        migrations.AddField(
            model_name='antwort',
            name='Frage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ausbildung.Frage', verbose_name='Questão'),
        ),
    ]
