# Generated by Django 2.2.6 on 2019-11-24 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ausbildung', '0003_antwort_fragetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antwort',
            name='Frage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ausbildung.Frage', verbose_name='Questão'),
        ),
    ]
