# Generated by Django 2.2.6 on 2019-10-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wortschatz', '0003_auto_20191025_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='abkurtzung',
            field=models.SlugField(max_length=4, unique=True, verbose_name='Abreviatura'),
        ),
    ]
