# Generated by Django 2.2.6 on 2019-10-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wortschatz', '0004_auto_20191026_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='land',
            options={'ordering': ['name', 'slug'], 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.RenameField(
            model_name='land',
            old_name='abkurtzung',
            new_name='slug',
        ),
    ]
