# Generated by Django 2.2.6 on 2019-10-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wortschatz', '0006_auto_20191029_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprache',
            name='slug',
            field=models.SlugField(max_length=7, unique=True, verbose_name='Abreviatura'),
        ),
    ]
