# Generated by Django 2.2.6 on 2019-10-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wortschatz', '0007_auto_20191029_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='land_sprache',
            options={'ordering': ['land', 'sprache', 'created', 'modified'], 'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
        migrations.AddField(
            model_name='land_sprache',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='land_sprache',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado em'),
        ),
    ]
