# Generated by Django 2.2.6 on 2019-10-29 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wortschatz', '0008_auto_20191029_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='land_sprache',
            options={'ordering': ['land', 'sprache', 'Amtssprache', 'created', 'modified'], 'verbose_name': 'Língua de País', 'verbose_name_plural': 'Línguas de Países'},
        ),
    ]
