# Generated by Django 2.2.6 on 2019-11-05 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Wortschatz', '0009_auto_20191029_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='land_sprache',
            options={'ordering': ['land', 'sprache', 'amtssprache', 'created', 'modified'], 'verbose_name': 'Idioma de País', 'verbose_name_plural': 'Idiomas de Países'},
        ),
        migrations.RenameField(
            model_name='land_sprache',
            old_name='Amtssprache',
            new_name='amtssprache',
        ),
        migrations.CreateModel(
            name='Wortschatz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubersetzung', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tradução')),
                ('wort', models.CharField(blank=True, max_length=200, null=True, verbose_name='Palavra')),
                ('bild', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('sprache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wortschatz.Sprache', verbose_name='Idioma compreendido')),
                ('sprachetraining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprachetraining', to='Wortschatz.Sprache', verbose_name='Idioma de treino')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Vocabulário',
                'verbose_name_plural': 'Vocabulários',
            },
        ),
        migrations.CreateModel(
            name='Benutzervorgaben',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('sprache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wortschatz.Sprache', verbose_name='Idioma compreendido')),
                ('sprachetraining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprachetraining_standard', to='Wortschatz.Sprache', verbose_name='Idioma de treino')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Usuário', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferência',
                'verbose_name_plural': 'Preferências',
            },
        ),
    ]
