# Generated by Django 2.2.6 on 2019-11-09 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wortschatz', '0010_auto_20191105_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benutzervorgaben',
            name='sprache',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Wortschatz.Sprache', verbose_name='Idioma compreendido'),
        ),
        migrations.AlterField(
            model_name='benutzervorgaben',
            name='sprachetraining',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprachetraining_standard', to='Wortschatz.Sprache', verbose_name='Idioma de treino'),
        ),
    ]
