# Generated by Django 2.2.6 on 2019-11-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wortschatz', '0011_auto_20191108_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wortschatz',
            name='bild',
            field=models.ImageField(blank=True, max_length=5000000, null=True, upload_to='', verbose_name='Imagem'),
        ),
    ]
