# Generated by Django 2.2.6 on 2019-11-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wortschatz', '0013_auto_20191114_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wortschatz',
            name='bild',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='Benutzer/', verbose_name='Imagem'),
        ),
    ]
