# Generated by Django 2.2.6 on 2019-11-21 15:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Wortschatz', '0014_auto_20191117_2211'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wortschatz',
            unique_together={('user', 'sprache', 'sprachetraining', 'ubersetzung', 'wort')},
        ),
    ]
