# Generated by Django 3.0 on 2020-02-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zugriff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
